# -*- coding: utf-8 -*-
"""Earthquake_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zt72208fdsbnul3j660nI9hcgD-z1qER
"""

# --- Installations---
!apt-get -qq install libgeos-dev
!pip install -q cartopy

#-- Imports --
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import LightSource
import seaborn as sns
from scipy import stats
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from sklearn.cluster import DBSCAN
import rasterio
from rasterio.merge import merge
from rasterio.plot import show
from sklearn.metrics import adjusted_rand_score, silhouette_score
import itertools
import matplotlib.lines as mlines
import cartopy.io.shapereader as shpreader
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
import matplotlib.patheffects as pe
import matplotlib.dates as mdates
from scipy import stats

np.random.seed(42) # Sets the global random state

# ---  Output Directory ---
OUTPUT_DIR = '/content/drive/MyDrive/Antu /Projects/EQ/Figure_v3'

# Create the folder if it doesn't exist
if not os.path.exists(OUTPUT_DIR):
    try:
        os.makedirs(OUTPUT_DIR)
        print(f"Created directory: {OUTPUT_DIR}")
    except OSError as e:
        print(f"Error creating directory: {e}")

# --- STYLE FUNCTION ---
def set_publication_style(type='single_column'):
    """
    Sets Matplotlib params for 'Geosystems and Geoenvironment' journal.
    """
    plt.style.use('default')

    # Dimensions
    if type == 'full_page':
        fig_width = 7.48
        fig_height = 5
    else:
        fig_width = 3.54
        fig_height = 3

    params = {
        'font.family': 'serif',
        'font.serif': ['Times New Roman', 'DejaVu Serif', 'serif'],
        'font.size': 6,
        'axes.labelsize': 8,
        'axes.titlesize': 10,
        'legend.fontsize': 6,
        'xtick.labelsize': 6,
        'ytick.labelsize': 6,

        'axes.linewidth': 0.8,
        'axes.grid': False,
        'lines.linewidth': 1.0,
        'lines.markersize': 3,

        'xtick.direction': 'out',
        'ytick.direction': 'out',
        'xtick.major.size': 2,
        'ytick.major.size': 2,
        'xtick.major.width': 0.3,
        'ytick.major.width': 0.3,
        'xtick.minor.size': 1,
        'ytick.minor.size': 1,

        'figure.figsize': (fig_width, fig_height),
        'figure.dpi': 150,
        'savefig.bbox': 'tight',
        'savefig.pad_inches': 0.05
    }
    plt.rcParams.update(params)

# --- 3. DUAL SAVE FUNCTION ---
def save_figure(filename):
    """
    Saves the current figure to Google Drive in BOTH .tif and .png formats.

    Args:
        filename (str): Name of file (e.g., 'Figure_1'). Extension not needed.
    """
    # Remove extension
    base_name = os.path.splitext(filename)[0]

    # Define paths
    path_tif = os.path.join(OUTPUT_DIR, f"{base_name}.tif")
    path_png = os.path.join(OUTPUT_DIR, f"{base_name}.png")

    # 1. Save TIFF
    plt.savefig(path_tif, dpi=1000, format='tif', pil_kwargs={"compression": "tiff_lzw"})

    # 2. Save PNG
    plt.savefig(path_png, dpi=1000, format='png')

    print(f"Saved successfully:\n  [TIFF] {path_tif}\n  [PNG]  {path_png}")

# --- APPLY STYLE ---
set_publication_style(type='single_column')

# 1. Define the path
file_path = '/content/drive/MyDrive/Antu /Projects/EQ/query.csv'

# 2. Read the CSV
df = pd.read_csv(file_path)

# 3. Check the first few rows
print(df.head())
print(df.info())
print(df.describe())

# --- 1. APPLY JOURNAL STYLE ---
set_publication_style(type='full_page')

# --- 2. FIGURE SETUP ---
fig = plt.figure(figsize=(7.48, 9))
ax = plt.axes(projection=ccrs.PlateCarree())

# --- PART A. PLOT DEM BACKGROUND ---
dem_path = '/content/drive/MyDrive/GEE_exports/DEM_500m.tif'

try:
    with rasterio.open(dem_path) as src:
        raw_dem_data = src.read(1)
        dem_extent = [src.bounds.left, src.bounds.right, src.bounds.bottom, src.bounds.top]

        # Ocean Masking
        ocean_mask = raw_dem_data < -100
        masked_land_dem = np.ma.masked_array(raw_dem_data, mask=ocean_mask)

        # Set Background Color (Sea)
        ax.set_facecolor('#4d4dc1')

        # Hillshading
        ls = LightSource(azdeg=315, altdeg=45)
        shaded_relief = ls.shade(masked_land_dem, cmap=plt.cm.terrain, vert_exag=0.1, blend_mode='soft', vmin=0, vmax=4000)

        ax.imshow(shaded_relief,
                  origin='upper',
                  extent=dem_extent,
                  transform=ccrs.PlateCarree(),
                  zorder=1)
        print("DEM Background loaded.")

except Exception as e:
    print(f"Could not load DEM: {e}. Using stock features.")
    ax.set_facecolor('#A6CEE3')
    ax.add_feature(cfeature.LAND)

# --- 4. Add Standard Map Features ---
ax.add_feature(cfeature.COASTLINE, linewidth=0.8, edgecolor='black', zorder=2)
ax.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.8, color='black', zorder=2)

# --- PART C: PLOT EARTHQUAKES ---
if 'df' in locals():
    sc = ax.scatter(df['longitude'], df['latitude'],
                    c=df['mag'],
                    s=df['mag']**2.5,
                    cmap='inferno_r',
                    alpha=0.8,
                    edgecolors='white',
                    linewidth=0.3,
                    transform=ccrs.PlateCarree(),
                    zorder=3)

    # Colorbar
    cbar = plt.colorbar(sc, label='Magnitude (Mw)', fraction=0.025, pad=0.03)
else:
    print("Warning: 'df' not found. Skipping scatter plot.")

# --- PART D: LABELS & FOCUS ---
ax.set_extent([82, 99.75, 17.5, 32], crs=ccrs.PlateCarree())

# Country Labels
labels = [
    (90.00, 24.00, 'Bangladesh'),
    (85.00, 23.00, 'India'),
    (92.25, 26.00, 'India'),
    (94.50, 23.00, 'Myanmar'),
    (90.00, 19.00, 'Bay of Bengal')
]

for lon, lat, name in labels:
    ax.text(lon, lat, name,
            transform=ccrs.Geodetic(),
            fontweight='bold',
            color='black',
            ha='center', va='center', zorder=4,
            # Add stroke to make text readable over terrain
            path_effects=[pe.withStroke(linewidth=1.5, foreground="white")])

# Gridlines
gl = ax.gridlines(draw_labels=True, linewidth=0.2, color='gray', alpha=0.3, linestyle='--', zorder=2)
gl.top_labels = False
gl.right_labels = False
gl.xlabel_style = {'size': plt.rcParams['xtick.labelsize'], 'color': 'black'}
gl.ylabel_style = {'size': plt.rcParams['ytick.labelsize'], 'color': 'black'}

# --- SAVE FOR SUBMISSION ---
# save_figure('Seismicity_Map_FullPage')

plt.show()

# --- 1. Apply Journal Style ---
set_publication_style(type='single_column')

# --- 2. Define the Center & Perform Projection ---
center_lat = df['latitude'].median()
center_lon = df['longitude'].median()

print(f"Projecting relative to center: {center_lat:.4f} N, {center_lon:.4f} E")

# Conversion Factors
# 1 deg Lat ~ 111.32 km
# 1 deg Lon ~ 111.32 * cos(lat)
lat_km_per_degree = 111.32
lon_km_per_degree = 111.32 * np.cos(np.radians(center_lat))

# Create New Columns
df['X_km'] = (df['longitude'] - center_lon) * lon_km_per_degree
df['Y_km'] = (df['latitude'] - center_lat) * lat_km_per_degree

# Check Data
print("\nFirst 5 rows with new coordinates:")
print(df[['latitude', 'longitude', 'X_km', 'Y_km']].head())

# --- 3. Plotting ---
fig, ax = plt.subplots()

# Scatter Plot
ax.scatter(df['X_km'], df['Y_km'],
           s=10,
           c='blue',
           alpha=0.6,
           edgecolors='none')

# Labels & formatting
ax.set_xlabel("Distance East-West (km)")
ax.set_ylabel("Distance North-South (km)")

ax.set_aspect('equal')

# --- 4. Save to Drive ---
# save_figure('Projected_Seismicity_Distribution')

plt.show()

import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Rectangle
from sklearn.cluster import HDBSCAN
from sklearn.metrics import silhouette_score

# --- DEFINE RANGES TO TEST ---
# Notice we dropped eps_range entirely.
alpha_range = [1, 2, 3, 4, 5]
min_cluster_size_range = [10, 15, 20, 25, 30]

# Generate combinations
param_grid = list(itertools.product(alpha_range, min_cluster_size_range))

print(f"Total HDBSCAN combinations to test: {len(param_grid)}")

results = []
total_points = len(df)

print("Running HDBSCAN Grid Search...")

for alpha, min_size in param_grid:

    # 1. Prepare data (Scale depth)
    temp_df = df.copy()
    temp_df["depth_weighted"] = temp_df["depth"] * alpha
    X = temp_df[["X_km", "Y_km", "depth_weighted"]].values

    # 2. Run HDBSCAN
    # We use min_cluster_size as the primary parameter.
    model = HDBSCAN(min_cluster_size=min_size)
    labels = model.fit_predict(X)

    # 3. Metrics
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    n_noise = np.sum(labels == -1)
    noise_pct = (n_noise / total_points) * 100

    if n_clusters > 1:
        mask = labels != -1
        try:
            sil = silhouette_score(X[mask], labels[mask])
        except:
            sil = np.nan
    else:
        sil = np.nan

    results.append({
        "alpha": alpha,
        "min_cluster_size": min_size,
        "n_clusters": n_clusters,
        "n_noise": n_noise,
        "noise_pct": noise_pct,
        "silhouette": sil
    })

res_df = pd.DataFrame(results)
print("Grid Search Complete.")

# Filter out models with excessive noise (e.g., > 50%)
MAX_NOISE_THRESHOLD = 50.0
valid_models = res_df[res_df['noise_pct'] <= MAX_NOISE_THRESHOLD]

# Get top 10 based on Silhouette Score
top_10 = valid_models.sort_values(by="silhouette", ascending=False).head(10)

print("\n--- Top 10 HDBSCAN Parameter Combinations ---")
display(top_10)

# Extract the absolute best parameters
best_params = top_10.iloc[0]
BEST_ALPHA = int(best_params['alpha'])
BEST_MIN_SIZE = int(best_params['min_cluster_size'])

print(f"\nBest Parameters Found: Alpha={BEST_ALPHA}, Min_Cluster_Size={BEST_MIN_SIZE}")

# --- 1. Apply Journal Style ---
# set_publication_style(type='full_page')

# --- 2. Pivot tables for Heatmaps ---
pivot_sil = res_df.pivot(index="alpha", columns="min_cluster_size", values="silhouette")
pivot_noise = res_df.pivot(index="alpha", columns="min_cluster_size", values="noise_pct")

# --- 3. Plotting ---
fig, axs = plt.subplots(1, 2, figsize=(12, 5), constrained_layout=True)

def highlight_cell(ax, pivot_table, target_col, target_row):
    try:
        col_idx = pivot_table.columns.get_loc(target_col)
        row_idx = pivot_table.index.get_loc(target_row)
        rect = Rectangle((col_idx, row_idx), 1, 1,
                         fill=False, edgecolor='red', lw=2.5, clip_on=False)
        ax.add_patch(rect)
    except KeyError:
        pass

# --- Plot 1: Silhouette Score ---
sns.heatmap(pivot_sil, annot=True, fmt=".3f", cmap="viridis", ax=axs[0],
            annot_kws={"size": 10}, cbar_kws={'label': 'Silhouette Score'})
axs[0].set_title("Clustering Quality (Silhouette)")
axs[0].set_xlabel("Minimum Cluster Size")
axs[0].set_ylabel("Depth Weight (α)")
axs[0].invert_yaxis() # Put Alpha=1 at the bottom
highlight_cell(axs[0], pivot_sil, BEST_MIN_SIZE, BEST_ALPHA)

# --- Plot 2: Noise Percentage ---
sns.heatmap(pivot_noise, annot=True, fmt=".1f", cmap="Reds", ax=axs[1],
            annot_kws={"size": 10}, cbar_kws={'label': '% Noise'})
axs[1].set_title("Data Loss (% Noise)")
axs[1].set_xlabel("Minimum Cluster Size")
axs[1].set_ylabel("Depth Weight (α)")
axs[1].invert_yaxis()
highlight_cell(axs[1], pivot_noise, BEST_MIN_SIZE, BEST_ALPHA)

# plt.savefig('HDBSCAN_Parameter_Space.pdf', dpi=300)
plt.show()

# # --- 1. Apply Journal Style ---
# # set_publication_style(type='single_column')

# # --- 2. Final HDBSCAN ---
# X_features_df = df[['X_km', 'Y_km', 'depth']].copy()
# X_features_df['depth'] = X_features_df['depth'] * 3 #BEST_ALPHA # Apply best depth weight
# X_features = X_features_df.values

# # Run final model
# final_model = HDBSCAN(min_cluster_size=30)  #BEST_MIN_SIZE
# df['Cluster'] = final_model.fit_predict(X_features)

# # Extract cluster probabilities (Exclusive to HDBSCAN, good for future analysis!)
# df['Cluster_Probability'] = final_model.probabilities_

# # --- 3. Visualization ---
# fig, ax = plt.subplots(figsize=(8, 8))

# # A. Plot Background Noise (-1)
# noise_data = df[df['Cluster'] == -1]
# ax.scatter(noise_data['X_km'], noise_data['Y_km'],
#            c='lightgrey', label='Background Seismicity',
#            s=5, alpha=0.5, edgecolors='none', zorder=1)

# # B. Plot Clusters
# cluster_data = df[df['Cluster'] != -1]
# scatter = ax.scatter(cluster_data['X_km'], cluster_data['Y_km'],
#                      c=cluster_data['Cluster'], cmap='tab20',
#                      s=12, alpha=0.8, edgecolors='none', zorder=2)

# ax.set_xlabel("Distance East-West (km)")
# ax.set_ylabel("Distance North-South (km)")
# ax.set_aspect('equal')

# # Legend and Colorbar
# ax.legend(loc='lower left', frameon=True, facecolor='white',
#           framealpha=1.0, edgecolor='black', fontsize=9)
# cbar = plt.colorbar(scatter, label='Cluster ID', fraction=0.03, pad=0.04)
# cbar.ax.tick_params(labelsize=9)

# # plt.savefig('HDBSCAN_Seismic_Zones.png')
# plt.show()

from sklearn.cluster import HDBSCAN

# --- 1. APPLY JOURNAL STYLE ---
# set_publication_style(type='single_column')

# --- 2. DATA PREP ---
BEST_ALPHA = 3.0
BEST_MIN_SIZE = 30

X_features_df = df[['X_km', 'Y_km', 'depth']].copy()
X_train = X_features_df.copy()
X_train['depth'] = X_train['depth'] * BEST_ALPHA

# Replaced DBSCAN with HDBSCAN
model = HDBSCAN(min_cluster_size=BEST_MIN_SIZE)
df['Cluster'] = model.fit_predict(X_train.values)

# Optional: Store cluster probabilities (Exclusive to HDBSCAN)
df['Cluster_Probability'] = model.probabilities_

noise_data = df[df['Cluster'] == -1]
cluster_data = df[df['Cluster'] != -1]

# --- 3. CALCULATE HEIGHT RATIOS ---
y_span = df['Y_km'].max() - df['Y_km'].min()
d_span = df['depth'].max()
height_ratios = [y_span, max(d_span, y_span * 0.2)]

# --- 4. PLOT SETUP ---
fig, (ax_map, ax_cs) = plt.subplots(2, 1,
                                    figsize=(3.54, 6),
                                    sharex=True,
                                    gridspec_kw={'height_ratios': height_ratios, 'hspace': 0.05})

# Background Noise
ax_map.scatter(noise_data['X_km'], noise_data['Y_km'], c='lightgrey',
               s=2, alpha=0.5, edgecolors='none', label='Noise')

# Clusters
sc = ax_map.scatter(cluster_data['X_km'], cluster_data['Y_km'],
                    c=cluster_data['Cluster'], cmap='tab20',
                    s=6, alpha=0.9, edgecolors='none')

ax_map.set_ylabel("N-S (km)")

# Alignment Magic
ax_map.set_aspect('equal', adjustable='box')
ax_map.set_anchor('S') # Pull down

# PLOT B: CROSS-SECTION (Bottom)
ax_cs.scatter(noise_data['X_km'], noise_data['depth'], c='lightgrey',
              s=2, alpha=0.5, edgecolors='none')

ax_cs.scatter(cluster_data['X_km'], cluster_data['depth'],
              c=cluster_data['Cluster'], cmap='tab20',
              s=6, alpha=0.9, edgecolors='none')

ax_cs.set_ylabel("Depth (km)")
ax_cs.set_xlabel("E-W (km)")

# Limits & Aspect
ax_cs.set_ylim(df['depth'].max()*1.05, 0)
ax_cs.set_aspect('equal', adjustable='box')
ax_cs.set_anchor('N') # Pull up

# 1. Force a draw to calculate positions
fig.canvas.draw()

# 2. Get exact bounding boxes
box_map = ax_map.get_position()
box_cs = ax_cs.get_position()

# 3. Calculate Colorbar Coordinates
cbar_left = max(box_map.x1, box_cs.x1) + 0.02
cbar_bottom = box_cs.y0
cbar_width = 0.03
cbar_height = box_map.y1 - box_cs.y0

# 4. Create Axes
ax_cbar = fig.add_axes([cbar_left, cbar_bottom, cbar_width, cbar_height])

# 5. Plot Colorbar
cbar = plt.colorbar(sc, cax=ax_cbar)
cbar.set_label('Cluster ID', rotation=270, labelpad=10)
cbar.ax.tick_params(labelsize=6)

# Legend (Small & Clean)
ax_map.legend(loc='upper right', frameon=True, facecolor='white', framealpha=1, fontsize=5, markerscale=2)

# --- 5. SAVE ---
# plt.savefig('Seismic_Structure_SingleCol')

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import HDBSCAN

# --- 1. RUN HDBSCAN ---
BEST_ALPHA = 5.0
BEST_MIN_SIZE = 15

X_features_df = df[['X_km', 'Y_km', 'depth']].copy()
X_features_df['depth'] = X_features_df['depth'] * BEST_ALPHA
X_features = X_features_df.values

final_model = HDBSCAN(min_cluster_size=BEST_MIN_SIZE)
df['Cluster'] = final_model.fit_predict(X_features)
df['Cluster_Probability'] = final_model.probabilities_

# --- 1. Apply Journal Style ---
# set_publication_style(type='full_page')

# --- 2. DEFINE CROSS-SECTION PROFILE ---
# INSERT YOUR SPECIFIC COORDINATES HERE (in km)
x_start, y_start = -400.0, 200.0  # Replace with your chosen starting X, Y
x_end, y_end = -50.0, 0.0     # Replace with your chosen ending X, Y
width_km = 20                   # Swath width

x0, y0 = x_start, y_start
x1, y1 = x_end, y_end

# --- 3. PROJECT EARTHQUAKES ONTO PROFILE ---
vec_line = np.array([x1 - x0, y1 - y0])
line_len = np.linalg.norm(vec_line)
vec_line_unit = vec_line / line_len
vec_line_perp = np.array([-vec_line_unit[1], vec_line_unit[0]])

pts_x = df['X_km'].values
pts_y = df['Y_km'].values
vec_pts_x = pts_x - x0
vec_pts_y = pts_y - y0

# Calculate distance along the line and perpendicular distance
dist_along = vec_pts_x * vec_line_unit[0] + vec_pts_y * vec_line_unit[1]
dist_perp = vec_pts_x * vec_line_perp[0] + vec_pts_y * vec_line_perp[1]

# Filter data within the swath box
mask = (dist_along >= 0) & (dist_along <= line_len) & (np.abs(dist_perp) <= width_km / 2)
df_sub = df[mask].copy()
df_sub['dist_along'] = dist_along[mask]

# --- 4. VISUALIZATION SETUP (SIDE-BY-SIDE) ---
fig, (ax_map, ax_cs) = plt.subplots(1, 2,figsize=(12, 6), gridspec_kw={'width_ratios': [1.2, 1], 'wspace': 0.25})

noise_data = df[df['Cluster'] == -1]
cluster_data = df[df['Cluster'] != -1]

# --- CRITICAL FIX: Get global min/max cluster IDs for consistent coloring ---
vmin_global = cluster_data['Cluster'].min()
vmax_global = cluster_data['Cluster'].max()

# --- PART A: LEFT MAP VIEW ---
ax_map.scatter(noise_data['X_km'], noise_data['Y_km'], c='lightgrey', s=5, alpha=0.5, edgecolors='none', zorder=1)

sc = ax_map.scatter(cluster_data['X_km'], cluster_data['Y_km'],
                    c=cluster_data['Cluster'], cmap='tab20',
                    vmin=vmin_global, vmax=vmax_global, # Force global color scale
                    s=12, alpha=0.8, edgecolors='none', zorder=2)

# Draw A-A' Line
ax_map.plot([x0, x1], [y0, y1], color='black', linewidth=1, zorder=1)
ax_map.text(x0, y0, 'A ', color='black', fontweight='bold', fontsize=9, ha='right', va='center')
ax_map.text(x1, y1, " A'", color='black', fontweight='bold', fontsize=9, ha='left', va='center')

# Draw Swath Box
box_x = [x0 + vec_line_perp[0]*width_km/2, x0 - vec_line_perp[0]*width_km/2,
         x1 - vec_line_perp[0]*width_km/2, x1 + vec_line_perp[0]*width_km/2, x0 + vec_line_perp[0]*width_km/2]
box_y = [y0 + vec_line_perp[1]*width_km/2, y0 - vec_line_perp[1]*width_km/2,
         y1 - vec_line_perp[1]*width_km/2, y1 + vec_line_perp[1]*width_km/2, y0 + vec_line_perp[1]*width_km/2]
ax_map.plot(box_x, box_y, 'k--', linewidth=1, alpha=0.8, zorder=3)

ax_map.set_xlabel("Distance East-West (km)")
ax_map.set_ylabel("Distance North-South (km)")
ax_map.set_aspect('equal')

# --- PART B: RIGHT CROSS-SECTION ---
noise_cs = df_sub[df_sub['Cluster'] == -1]
clusters_cs = df_sub[df_sub['Cluster'] != -1]

ax_cs.scatter(noise_cs['dist_along'], noise_cs['depth'], c='lightgrey', s=10, alpha=0.5, edgecolors='none')

ax_cs.scatter(clusters_cs['dist_along'], clusters_cs['depth'],
              c=clusters_cs['Cluster'], cmap='tab20',
              vmin=vmin_global, vmax=vmax_global, # Force global color scale
              s=25, alpha=0.9, edgecolors='black', linewidth=0.3)

ax_cs.set_xlim(0, line_len)
ax_cs.set_ylim(80, -2) # Invert Y axis

ax_cs.set_xlabel("Distance along profile A-A' (km)")
ax_cs.set_ylabel("Depth (km)")
ax_cs.grid(False)

# --- 5. COLORBAR ---
cbar = plt.colorbar(sc, ax=ax_map, fraction=0.03, pad=0.04)
cbar.set_label('Cluster ID', rotation=270, labelpad=15)

# --- 6. ALIGNMENT MAGIC ---
# Force matplotlib to calculate the final rendered sizes
fig.canvas.draw()

# Get the exact bounding boxes after the 'equal' aspect ratio and colorbar are applied
pos_map = ax_map.get_position()
pos_cs = ax_cs.get_position()

# Override the cross-section's position to perfectly match the map's bottom and height
ax_cs.set_position([pos_cs.x0, pos_map.y0, pos_cs.width, pos_map.height])

# plt.savefig('HDBSCAN_SideBySide_CrossSection.pdf', dpi=300, bbox_inches='tight')
plt.show()

# Store results
geometry_data = []

for cluster_id in sorted(df['Cluster'].unique()):
    if cluster_id == -1: continue # Skip noise

    # 1. Get the X, Y, Z data
    cluster_points = df[df['Cluster'] == cluster_id][['X_km', 'Y_km', 'depth']].values

    # We need at least 3 points to define a plane
    if len(cluster_points) < 3:
        continue

    # 2. Run PCA to find the orientation
    pca = PCA(n_components=3)
    pca.fit(cluster_points)

    # 3. Get the "Normal Vector" (The 3rd component, representing thickness)
    normal_vector = pca.components_[2]

    # 4. Calculate Dip Angle
    vertical_component = abs(normal_vector[2])

    # Calculate angle in radians, then convert to degrees
    dip_rad = np.arccos(vertical_component)
    dip_deg = np.degrees(dip_rad)

    geometry_data.append({
        'Cluster_ID': cluster_id,
        'Dip_Angle': round(dip_deg, 1),
        'Num_Events': len(cluster_points)
    })

# Convert to DataFrame
geo_df = pd.DataFrame(geometry_data)
print(geo_df)

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

# --- SETTINGS ---
MIN_EVENTS_FOR_B = 10
MIN_DIP_ANGLE = 1.0  # Threshold to filter out flat 10km artifacts (0 degrees)

# --- 1. Define the Optimized b-value function ---
def calculate_b_value_advanced(magnitudes, delta_m=0.1, min_events=MIN_EVENTS_FOR_B):
    """
    Calculates Mc, b-value, and standard error using MAXC+0.2 and MLE.
    """
    magnitudes = np.round(magnitudes, 1)
    counts = magnitudes.value_counts().sort_index()

    if len(counts) == 0:
        return np.nan, np.nan, np.nan

    # Automatic Mc Estimation: MAXC + Correction
    maxc = counts.idxmax()
    mc = np.round(maxc + 0.2, 1)

    # Filter Data
    valid_mags = magnitudes[magnitudes >= mc]
    N = len(valid_mags)

    # Safety Check
    if N < min_events:
        return np.nan, mc, np.nan

    # Calculate b-value (Aki-Utsu Maximum Likelihood Estimation)
    avg_mag = np.mean(valid_mags)
    b_val = np.log10(np.e) / (avg_mag - (mc - (delta_m / 2)))

    # Calculate Standard Error (Shi & Bolt, 1982)
    b_err = b_val / np.sqrt(N)

    return b_val, mc, b_err

# --- 2. Calculate Geometry & b-value for each Cluster ---
cluster_stats = []

# Ensure 'mag' column is numeric
df['mag'] = pd.to_numeric(df['mag'], errors='coerce')

flat_artifacts_dropped = 0

for cluster_id in sorted(df['Cluster'].unique()):
    if cluster_id == -1: continue # Skip background seismicity

    # --- STEP A: GEOMETRY CHECK (Filter out flat artifacts) ---
    cluster_points = df[df['Cluster'] == cluster_id][['X_km', 'Y_km', 'depth']].values

    if len(cluster_points) < 3:
        continue

    pca = PCA(n_components=3)
    pca.fit(cluster_points)
    normal_vector = pca.components_[2]

    vertical_component = abs(normal_vector[2])
    dip_rad = np.arccos(vertical_component)
    dip_deg = np.degrees(dip_rad)

    # Check if this is a 10km fixed-depth artifact (~0 degrees)
    if dip_deg < MIN_DIP_ANGLE:
        flat_artifacts_dropped += 1
        continue # Skip this cluster entirely

    # --- STEP B: B-VALUE CALCULATION (For valid geological structures) ---
    mags = df[df['Cluster'] == cluster_id]['mag']

    b, calculated_mc, b_err = calculate_b_value_advanced(mags, min_events=MIN_EVENTS_FOR_B)

    center_x = df[df['Cluster'] == cluster_id]['X_km'].mean()
    center_y = df[df['Cluster'] == cluster_id]['Y_km'].mean()
    total_events = len(mags)
    events_above_mc = len(mags[mags >= calculated_mc]) if not np.isnan(calculated_mc) else 0

    cluster_stats.append({
        'Cluster_ID': cluster_id,
        'Dip_Angle': round(dip_deg, 1),
        'b_value': b,
        'b_error': b_err,
        'Mc_used': calculated_mc,
        'Total_Events': total_events,
        'Events_Above_Mc': events_above_mc,
        'X_km': center_x,
        'Y_km': center_y
    })

# --- 3. Format and Display Results ---
stats_df = pd.DataFrame(cluster_stats)

print("--- Seismic Hazard Assessment ---")
# Show valid results, sorted by risk (low b-value = higher stress/hazard)
results = stats_df.dropna(subset=['b_value']).sort_values(by='b_value')

# Clean formatting for the final table
display_cols = ['Cluster_ID', 'Dip_Angle', 'b_value', 'b_error', 'Mc_used', 'Total_Events', 'Events_Above_Mc']
results_print = results[display_cols].copy()

# Integers for counts/IDs
results_print['Cluster_ID'] = results_print['Cluster_ID'].astype(int)
results_print['Total_Events'] = results_print['Total_Events'].astype(int)
results_print['Events_Above_Mc'] = results_print['Events_Above_Mc'].astype(int)

# Formatted floats for stats
results_print['Dip_Angle'] = results_print['Dip_Angle'].map('{:.1f}°'.format)
results_print['b_value'] = results_print['b_value'].map('{:.3f}'.format)
results_print['b_error'] = results_print['b_error'].map('{:.3f}'.format)
results_print['Mc_used'] = results_print['Mc_used'].map('{:.2f}'.format)

print(results_print.to_string(index=False))

# Check dropped clusters
dropped_b_value = stats_df['b_value'].isna().sum()

print(f"\n--- Data Quality Report ---")
print(f"Artifacts Removed: {flat_artifacts_dropped} clusters were dropped because they were flat horizontal artifacts (Dip < {MIN_DIP_ANGLE}°).")
print(f"Low Data Removed:  {dropped_b_value} valid clusters were skipped because they had fewer than {MIN_EVENTS_FOR_B} events above Mc.")

# --- 1. APPLY JOURNAL STYLE ---
# set_publication_style(type='single_column')

# --- 2. PREPARE DATA ---
# Map b-values
b_val_dict = stats_df.set_index('Cluster_ID')['b_value'].to_dict()
df['b_value_mapped'] = df['Cluster'].map(b_val_dict)

# Separate Groups
# Note: Clusters dropped due to flat 0° dip or N < 10 will automatically
# fall into the 'unknown_hazard' category and plot as grey.
noise_data = df[df['Cluster'] == -1]
unknown_hazard = df[(df['Cluster'] != -1) & (df['b_value_mapped'].isna())]
analyzed_data = df[(df['Cluster'] != -1) & (df['b_value_mapped'].notna())]

# --- 3. PLOT SETUP ---
fig, ax = plt.subplots(figsize=(7,9))

# Layer 1: Noise
ax.scatter(noise_data['X_km'], noise_data['Y_km'],
           c='lightgrey', s=2, alpha=0.3, label='Background')

# Layer 2: Insufficient Data / Excluded Artifacts
ax.scatter(unknown_hazard['X_km'], unknown_hazard['Y_km'],
           c='grey', s=6, alpha=0.5, label='Insufficient Data')

# Layer 3: The Danger Map (b-values)
# RdYlGn: Red=Low b (High Stress), Green=High b (Low Stress)
sc = ax.scatter(analyzed_data['X_km'], analyzed_data['Y_km'],
                c=analyzed_data['b_value_mapped'],
                cmap='RdYlGn',
                vmin=0.6, vmax=1.2,
                s=12, alpha=0.9, edgecolors='black', linewidth=0.2)

# --- 4. FORMATTING ---
ax.set_xlabel('E-W (km)')
ax.set_ylabel('N-S (km)')
ax.set_aspect('equal')

# Colorbar
cbar = plt.colorbar(sc, ax=ax, fraction=0.04, pad=0.04)
cbar.set_label('b-value', rotation=270, labelpad=10)
cbar.ax.tick_params(labelsize=6)

# --- 5. SMART LABELING ---
# We loop through stats_df to label significant clusters
for index, row in stats_df.iterrows():
    if pd.notna(row['b_value']):
        # CONDITION: Label if DANGEROUS (b < 0.8) or VERY ACTIVE (> 50 events)
        # CHANGED: 'Num_Events_Total' updated to 'Total_Events' to match new stats_df
        if row['b_value'] < 0.8 or row['Total_Events'] > 50:

            # Using standard label, but if you want to include standard error,
            # you can change this to: f"C{int(row['Cluster_ID'])}\nb={row['b_value']:.2f}±{row['b_error']:.2f}"
            label_text = f"C{int(row['Cluster_ID'])}\nb={row['b_value']:.2f}"

            # Style: Red/Bold for dangerous clusters
            text_color = 'red' if row['b_value'] < 0.8 else 'black'
            weight = 'bold' if row['b_value'] < 0.8 else 'normal'

            ax.text(row['X_km'], row['Y_km'], label_text,
                    fontsize=5, # Small font for labels
                    fontweight=weight,
                    color=text_color,
                    ha='center', va='center',
                    bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', boxstyle='round,pad=0.1'))

# Legend (Upper Right, Compact)
ax.legend(loc='upper right', frameon=True, facecolor='white', framealpha=1, fontsize=5, markerscale=2)

# --- 6. SAVE ---
# plt.savefig('Seismic_Hazard_Map_b_values.pdf', dpi=300, bbox_inches='tight')

plt.show()

import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString
from sklearn.decomposition import PCA
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# --- 1. FILTER FOR VALID CLUSTERS ---
valid_clusters = stats_df.dropna(subset=['b_value'])['Cluster_ID'].values

fault_features = []

print(f"Extracting 3D curved fault traces for {len(valid_clusters)} valid clusters...")

# --- 2. GENERATE 3D CURVED FAULT LINES ---
for cluster_id in valid_clusters:
    cluster_data = df[df['Cluster'] == cluster_id]

    if len(cluster_data) < 3:
        continue # Need at least 3 points for a curve

    # Extract 3D coordinates
    lons = cluster_data['longitude'].values
    lats = cluster_data['latitude'].values
    depths = cluster_data['depth'].values

    # Step A: Use 2D PCA to find the primary map-view strike direction
    pca = PCA(n_components=2).fit(np.column_stack((lons, lats)))
    is_vertical = abs(pca.components_[0][1]) > abs(pca.components_[0][0])

    # Step B: Select independent variable to prevent near-infinite slopes
    x_reg = lats if is_vertical else lons
    y_reg = lons if is_vertical else lats
    z_reg = depths # Dependent variable for depth

    # Step C: Fit 2nd-Degree Polynomials for both Geography and Depth
    poly = PolynomialFeatures(degree=2)
    X_poly = poly.fit_transform(x_reg.reshape(-1, 1))

    model_xy = LinearRegression().fit(X_poly, y_reg)
    model_z = LinearRegression().fit(X_poly, z_reg) # New model for depth

    # Step D: Generate smooth points
    x_range = np.linspace(x_reg.min(), x_reg.max(), 50).reshape(-1, 1)
    X_range_poly = poly.transform(x_range)

    y_pred = model_xy.predict(X_range_poly)
    z_pred = model_z.predict(X_range_poly) # Predict depth curve

    # Step E: Recombine into 3D (Longitude, Latitude, Depth) arrays
    if is_vertical:
        line_points = np.column_stack((y_pred, x_range.flatten(), z_pred))
    else:
        line_points = np.column_stack((x_range.flatten(), y_pred, z_pred))

    # Step F: Convert to a 3D Shapely spatial object
    # Shapely seamlessly accepts (x, y, z) tuples
    fault_line = LineString(line_points)

    cluster_stats = stats_df[stats_df['Cluster_ID'] == cluster_id].iloc[0]

    fault_features.append({
        'Cluster_ID': cluster_id,
        'b_value': cluster_stats['b_value'],
        'b_error': cluster_stats['b_error'],
        'Dip_Angle': cluster_stats['Dip_Angle'],
        'geometry': fault_line
    })

# --- 3. CREATE IN-MEMORY SHAPEFILE (GeoDataFrame) ---
faults_gdf = gpd.GeoDataFrame(fault_features, crs="EPSG:4326")

print("\n--- In-Memory 3D Fault Line GeoDataFrame Created ---")
print(faults_gdf[['Cluster_ID', 'b_value', 'Dip_Angle', 'geometry']].head())

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.lines as mlines
import matplotlib.patheffects as pe
import numpy as np
import pandas as pd
import rasterio
import cartopy.io.shapereader as shpreader
from matplotlib.colors import LightSource

# --- 1. APPLY JOURNAL STYLE ---
# set_publication_style(type='full_page')

# --- 2. CONFIGURATION ---
buffer = 0.5 # Reduced buffer slightly for tighter view
min_lon, max_lon = df['longitude'].min() - buffer, df['longitude'].max() + buffer
min_lat, max_lat = df['latitude'].min() - buffer, df['latitude'].max() + buffer

# --- 3. FIGURE SETUP (MAP ONLY) ---
# Adjusted figure size to be more square since we removed the bottom panel
fig = plt.figure(figsize=(8, 8))

# Initial Placeholder Positions [Left, Bottom, Width, Height]
ax_map = fig.add_axes([0.1, 0.1, 0.75, 0.8], projection=ccrs.PlateCarree())
ax_cbar = fig.add_axes([0.88, 0.1, 0.02, 0.8])

ax_map.set_extent([min_lon, max_lon, min_lat, max_lat], crs=ccrs.PlateCarree())

# ==========================================
# PART A: MAP VIEW
# ==========================================

# 1. Background (DEM)
dem_path = '/content/drive/MyDrive/GEE_exports/DEM_500m_v2.tif'
try:
    with rasterio.open(dem_path) as src:
        raw_dem_data = src.read(1)
        dem_extent = [src.bounds.left, src.bounds.right, src.bounds.bottom, src.bounds.top]
        ocean_mask = raw_dem_data < -100
        masked_land_dem = np.ma.masked_array(raw_dem_data, mask=ocean_mask)

        ax_map.set_facecolor('#4d4dc1')
        ls = LightSource(azdeg=315, altdeg=45)
        shaded_relief = ls.shade(masked_land_dem, cmap=plt.cm.terrain, vert_exag=0.1, blend_mode='soft', vmin=0, vmax=4000)
        ax_map.imshow(shaded_relief, origin='upper', extent=dem_extent, transform=ccrs.PlateCarree(), zorder=1)
except:
    ax_map.set_facecolor('#A6CEE3')
    ax_map.add_feature(cfeature.LAND)

# 2. Features & Lat/Lon Gridlines
ax_map.add_feature(cfeature.COASTLINE, linewidth=0.8, zorder=2)
ax_map.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.8, zorder=2)

gl = ax_map.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                      color='gray', alpha=0.5, linestyle='--')
gl.top_labels = False
gl.right_labels = False
gl.xlabel_style = {'size': 9}
gl.ylabel_style = {'size': 9}

# 3. Earthquakes (b-value colored)
b_val_dict = stats_df.set_index('Cluster_ID')['b_value'].to_dict()
df['b_value_mapped'] = df['Cluster'].map(b_val_dict)
map_data = df[(df['Cluster'] != -1) & (df['b_value_mapped'].notna())]

sc = ax_map.scatter(map_data['longitude'], map_data['latitude'],
                    c=map_data['b_value_mapped'], cmap='RdYlGn', vmin=0.6, vmax=1.2,
                    s=15, alpha=0.9, transform=ccrs.PlateCarree(),
                    edgecolors='black', linewidth=0.2, zorder=3)

# 4. Inferred Faults (Using the clean GeoDataFrame from earlier)
try:
    faults_gdf.plot(ax=ax_map, color='black', linewidth=1.5, alpha=0.8, transform=ccrs.PlateCarree(), zorder=4)
except NameError:
    print("Warning: faults_gdf not found. Please run the curved fault line generation block first.")

# 5. Shapefiles
shapefiles_config = [
    {'path': '/content/drive/MyDrive/Antu /Projects/EQ/Shape file/Major Plate Boundaries.shp',
     'color': 'red', 'lw': 1.5, 'ls': '-', 'label': 'Major Plate Boundary'},
    {'path': '/content/drive/MyDrive/Antu /Projects/EQ/Shape file/Micro_plate and Major Faults.shp',
     'color': '#FFA500', 'lw': 1.0, 'ls': '--', 'label': 'Micro Plate / Major Fault'}
]
for sf in shapefiles_config:
    try:
        reader = shpreader.Reader(sf['path'])
        ax_map.add_geometries(reader.geometries(), ccrs.PlateCarree(),
                              facecolor='none', edgecolor=sf['color'], linewidth=sf['lw'],
                              linestyle=sf['ls'], alpha=1.0, zorder=5)
    except: pass

# 6. Labels
labels = [(90.00, 24.30, 'Bangladesh'), (87.00, 23.00, 'India'), (92.25, 26.00, 'India'), (94.50, 23.00, 'Myanmar')]
for lon, lat, name in labels:
    ax_map.text(lon, lat, name, transform=ccrs.PlateCarree(), fontsize=8, fontweight='bold',
                ha='center', va='center', zorder=5, path_effects=[pe.withStroke(linewidth=1.5, foreground="white")])

# Legend
legend_handles = [
    mlines.Line2D([], [], color='black', linewidth=1.5, label='Inferred Fault'),
    mlines.Line2D([], [], color='red', linewidth=1.5, linestyle='-', label='Plate Boundary'),
    mlines.Line2D([], [], color='#FFA500', linewidth=1.0, linestyle='--', label='Major Fault')
]
ax_map.legend(handles=legend_handles, loc='lower left', frameon=True, fontsize=8, facecolor='white', framealpha=1.0)

# --- SMART LABELING (With Stacking & Overlap Prevention) ---
labels_to_plot = []
lon_tol = (max_lon - min_lon) * 0.06
lat_tol = (max_lat - min_lat) * 0.06

for index, row in stats_df.iterrows():
    cluster_id = row['Cluster_ID']
    b_val = row['b_value']
    b_err = row['b_error']

    if pd.isna(b_val) or cluster_id == -1:
        continue

    cluster_subset = df[df['Cluster'] == cluster_id]
    if cluster_subset.empty:
        continue

    cent_lat = cluster_subset['latitude'].mean()
    cent_lon = cluster_subset['longitude'].mean()

    label_text = f"C{int(cluster_id)}: b={b_val:.2f}±{b_err:.2f}"
    is_hazardous = (b_val < 0.8)

    overlap_found = False
    for placed in labels_to_plot:
        if abs(cent_lon - placed['lon']) < lon_tol and abs(cent_lat - placed['lat']) < lat_tol:
            placed['text'] += f"\n{label_text}"
            placed['hazard'] = placed['hazard'] or is_hazardous
            overlap_found = True
            break

    if not overlap_found:
        labels_to_plot.append({
            'lon': cent_lon,
            'lat': cent_lat,
            'text': label_text,
            'hazard': is_hazardous
        })

for lbl in labels_to_plot:
    if lbl['hazard']:
        box_color, edge_color, font_weight = 'white', 'red', 'bold'
    else:
        box_color, edge_color, font_weight = 'white', 'grey', 'normal'

    lon_margin = (max_lon - min_lon) * 0.12
    lat_margin = (max_lat - min_lat) * 0.12

    text_ha, text_va = 'center', 'bottom'

    if lbl['lon'] < min_lon + lon_margin: text_ha = 'left'
    elif lbl['lon'] > max_lon - lon_margin: text_ha = 'right'

    if lbl['lat'] > max_lat - lat_margin: text_va = 'top'
    elif lbl['lat'] < min_lat + lat_margin: text_va = 'bottom'

    ax_map.text(lbl['lon'], lbl['lat'], lbl['text'],
            transform=ccrs.PlateCarree(),
            ha=text_ha, va=text_va,
            fontsize=4, fontweight=font_weight, # Reduced font size to 4
            bbox=dict(facecolor=box_color, edgecolor=edge_color, alpha=0.9, boxstyle='round,pad=0.15'), # Reduced padding to 0.15
            zorder=10)

# ==========================================
# PART B: ALIGNMENT & FINAL DETAILS
# ==========================================

# 1. Force a draw
fig.canvas.draw()

# 2. Get the ACTUAL bounding box of the map on screen
map_pos = ax_map.get_position()

# 3. Update Colorbar Position to match map height perfectly
# Left = Map Right + Padding
ax_cbar.set_position([map_pos.x1 + 0.02, map_pos.y0, 0.02, map_pos.height])

# FINAL DETAILS & SAVE
cbar = plt.colorbar(sc, cax=ax_cbar)
cbar.set_label('b-value (Hazard)', rotation=270, labelpad=15)
cbar.ax.tick_params(labelsize=8)

# Save
# plt.savefig('Seismic_Hazard_MapOnly.pdf', dpi=300, bbox_inches='tight')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# --- 1. APPLY JOURNAL STYLE ---
# set_publication_style(type='single_column')

def plot_gutenberg_richter(df, stats_df, cluster_id):
    """
    Generates a standard seismological FMD plot (Discrete and Cumulative)
    with the theoretical Aki MLE fit line.
    """
    # --- 1. Extract Data ---
    mags = df[df['Cluster'] == cluster_id]['mag'].dropna()
    mags = np.round(mags, 1) # Ensure consistent 0.1 binning

    # Get cluster statistics
    cluster_info = stats_df[stats_df['Cluster_ID'] == cluster_id]

    if cluster_info.empty:
        print(f"Cluster {cluster_id} not found in stats_df.")
        return

    cluster_info = cluster_info.iloc[0]
    b_val = cluster_info['b_value']
    b_err = cluster_info['b_error']
    mc = cluster_info['Mc_used']

    if pd.isna(b_val):
        print(f"Cannot plot Cluster {cluster_id}: Insufficient data for b-value.")
        return

    # --- 2. Calculate FMD (Discrete & Cumulative) ---
    # Discrete counts (Non-cumulative)
    counts = mags.value_counts().sort_index()
    mag_bins = counts.index.values
    discrete_N = counts.values

    # Cumulative counts (N >= M)
    cumulative_N = counts[::-1].cumsum()[::-1].values

    # --- 3. Calculate Theoretical Fit Line (log10 N = a - bM) ---
    # Find the cumulative count exactly at Mc to anchor the line
    try:
        idx_mc = np.where(np.isclose(mag_bins, mc))[0][0]
        N_mc = cumulative_N[idx_mc]
    except IndexError:
        print("Mc not found exactly in magnitude bins. Fallback used.")
        N_mc = len(mags[mags >= mc])

    # Derive 'a' value: a = log10(N_mc) + b * Mc
    a_val = np.log10(N_mc) + (b_val * mc)

    # Generate line data from Mc to the max magnitude
    fit_mags = np.linspace(mc, mag_bins.max() + 0.5, 50)
    fit_N = 10**(a_val - b_val * fit_mags)

    # --- 4. Plotting Setup ---
    fig, ax = plt.subplots(figsize=(4.5, 4.5))

    # Plot Discrete Data
    ax.scatter(mag_bins, discrete_N,
               marker='^', facecolors='none', edgecolors='grey', s=30,
               label='Discrete (Non-cumulative)')

    # Plot Cumulative Data (Using a raw string r'...' to fix \geq)
    ax.scatter(mag_bins, cumulative_N,
               marker='s', color='black', s=30,
               label=r'Cumulative ($N \geq M$)')

    # Draw Mc vertical cutoff line
    ax.axvline(x=mc, color='red', linestyle='--', linewidth=1.5,
               label=rf'$M_c$ = {mc:.1f}')

    # Draw the theoretical Aki MLE line
    ax.plot(fit_mags, fit_N, color='blue', linewidth=2.0,
            label='Aki MLE Fit')

    # --- 5. Formatting ---
    ax.set_yscale('log') # FMD plots MUST be logarithmic
    ax.set_xlabel('Magnitude ($M$)')
    ax.set_ylabel('Number of Earthquakes ($N$)')

    # Set axis limits to look clean
    ax.set_xlim(max(mag_bins.min() - 0.5, 0), mag_bins.max() + 0.5)
    ax.set_ylim(0.5, cumulative_N.max() * 2)

    # --- 6. Stats Text Box (Using raw f-strings rf"..." to fix \pm and \geq) ---
    stats_text = (
        rf"$b$-value: {b_val:.2f} $\pm$ {b_err:.2f}" + "\n"
        rf"$a$-value: {a_val:.2f}" + "\n"
        rf"$M_c$: {mc:.1f}" + "\n"
        rf"$N_{{total}}$: {len(mags)}" + "\n"
        rf"$N \geq M_c$: {N_mc}"
    )

    ax.text(0.95, 0.95, stats_text,
            transform=ax.transAxes, fontsize=9,
            verticalalignment='top', horizontalalignment='right',
            bbox=dict(facecolor='white', edgecolor='black', alpha=0.9, boxstyle='round,pad=0.5'))

    # Add legend
    ax.legend(loc='lower left', fontsize=8, framealpha=1.0)

    plt.tight_layout()
    # plt.savefig(f'FMD_Cluster_{int(cluster_id)}.pdf', dpi=300)
    plt.show()

# --- RUN IT FOR A SPECIFIC CLUSTER ---
TARGET_CLUSTER = 33  # <-- Change this to whichever cluster ID you want to plot

print(f"Plotting FMD for Cluster {TARGET_CLUSTER}...")
plot_gutenberg_richter(df, stats_df, TARGET_CLUSTER)